# Generated by Django 6.0.2 on 2026-03-05 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.TextField(unique=True)),
                ('model', models.TextField()),
                ('firmware_version', models.TextField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.organisation')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('co2_ppm', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('noise_db', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('cpu_temp', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('firmware_version', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('organisation', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, to='api.organisation')),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='api.sensor')),
            ],
            options={
                'db_table': 'telemetry',
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['organisation'], name='idx_sensors_org'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['-time'], name='idx_telemetry_time'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['sensor', '-time'], name='idx_telemetry_sensor_time'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['organisation', '-time'], name='idx_telemetry_org_time'),
        ),
        migrations.AddConstraint(
            model_name='telemetry',
            constraint=models.UniqueConstraint(fields=('time', 'sensor'), name='telemetry_unique_time_sensor'),
        ),
    ]
