# Generated by Django 6.0.2 on 2026-03-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS timescaledb;"
        ),
        migrations.RunSQL(
            sql="alter table telemetry drop constraint telemetry_pkey;"
        ),
        migrations.RunSQL(
            sql="alter table telemetry add primary key (time,id);"
        ),
        migrations.RunSQL(
            sql="select create_hypertable('telemetry', 'time', if_not_exists => true);",
            reverse_sql="select drop_chunk('telemetry', INTERVAL '100 years');"
        ),
        migrations.RunSQL(
            sql=" select set_chunk_time_interval('telemetry', INTERVAL '1 day');"
        )
    ]
