# Generated by Django 6.0.2 on 2026-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260305_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
